allowed licenses: []

files to check:
    - requirements.txt
    - requirements-dev.txt
    - setup.cfg

language: python

include:
    - https://codeberg.org/frnmst/licheck/raw/branch/master/examples/python_gpl_compatible.yml
